### ISSUE TITLE
error correct for readme.md

### ISSUE THREAD

**Issue by T-I-Oak** [Kray-G/kinx#1]
* Motivation 2
  * nodejs => node.js
* Auto-loaded Objects
  * `Sysrem` => `System`

**Comment by Kray-G** [comment]
Thanks for your report.
I corrected it with https://github.com/Kray-G/kinx/commit/eaede269d349304f137c6e9ffba7e3a86ea5f3db.

Thanks again.

**Comment by Kray-G** [comment]
closed.
