### ISSUE TITLE
Things we can do with kinx?

### ISSUE THREAD

**Issue by Krrishdhaneja** [Kray-G/kinx#146]
I found this project in the explore section and found it to be way too interesting. So the question here is, what can i do with kinx as it is not mentioned in the documentation?

**Comment by Krrishdhaneja** [comment]
And one more doubt is there, i want to contribute to this project, how and where from I start?

**Comment by Krrishdhaneja** [comment]
@Kray-G ?

**Comment by Kray-G** [comment]
Thank you for your interest. I feel very happy for your offer.
Now what I should take much time is to complete an incomplete documentation.
Any contribution will be welcome, but if I say somthing...

* Would you ikke to become a user of Kinx?
  * Read a document, and find out a mistake or a strange point in the document.
  * Use Kinx to solve your problem if possible.
  * Create a software or a tool written in Kinx.
* Bug report or any suggestion of new feature.
  * If you find something bad, please let me know about it as an issue.
  * If there is something you want as a new feature, please et me know as a feature request.

If you have any idea, please try to do it and whatever the product will improve will be pleasure for me.

Thanks in advance.

**Comment by Krrishdhaneja** [comment]
For learning kinx what do i need to do @Kray-G ?

**Comment by Kray-G** [comment]
Hi @Krrishdhaneja 

First you can read a document on [Kinx Specification](https://github.com/Kray-G/kinx/blob/master/docs/index.md).

About installation, please read a section of **How to Install** in [README.md](https://github.com/Kray-G/kinx) at the top page.
You can install it via Scoop or an installer for Windows.
For Linux, download `.deb` for Ubuntu at the [Releases](https://github.com/Kray-G/kinx/releases) page, or you can clone and build it on your linux environment.

Please try it.

Thank you.

**Comment by Krrishdhaneja** [comment]
I would be definitely trying it.

**Comment by Kray-G** [comment]
Thanks for many things to this product.
I hope you will be a user and launch some repository of your own with Kinx, if possible.

This issue is closed once, but welcome to your any report if you have any question or bugs.

Thanks in advance.
