### ISSUE TITLE
doc comment について

### ISSUE THREAD

**Issue by htsign** [Kray-G/kinx#16]
Kinx でプログラムを組むにあたり、ドキュメントコメントはどういった方針がよいのでしょう？
特に型については是非ともコメントに書いておきたい、という気持ちがあります。
（まずそもそもドキュメントコメントを言語仕様に含めるのかどうかという疑問もあります）

```javascript
/**
 * ブロックコメントを使うスタイル (JS, Java など)
 * @param {Array<Integer>} xs - values
 * @returns {Integer} sum
 */
function sum(xs) {
    return xs.reduce(&(acc, x) => acc + x, 0);
}
```

```coffee
%{
docstring (Python など)

Parameters
----------
xs : Array<Integer>
    values

Returns
-------
sumValue : Integer
    sum
}
function sum(xs) {
    return xs.reduce(&(acc, x) => acc + x, 0);
}
```

```javascript
# コードに埋めこむスタイル
/* Integer */ function sum(/* Array<Integer> */ xs) {
    return xs.reduce(&(acc, x) => acc + x, 0);
}
```

またはその他。

---

便宜上配列の型を `Array<T>` で表記しましたが、これも `Array[A]` (Scala, Nim など) とか `[T]` (Swift, Haskell など) とか `'a array` (OCaml など) とか `T[]` (TypeScript での別表記) とかいろいろあります。

**Comment by Kray-G** [comment]
いいですね、ドキュメント・コメントを言語仕様に入れてしまうのはアリです。というか、私自身は悪いプログラマ（←すみません...）なのでコメントをほとんど書いておらず、警告されるとちゃんと書くかもしれません。。。

個人的には most fitting in C programmers が目標なので Javadoc style でしょうか。言語仕様に組み込んでしまう案に1票です。

特にライブラリ系は無いと使う側が困りますよね。。

**Comment by htsign** [comment]
Javadoc style ですね。ありがとうございます。
ところで改めて quick reference を拝見したのですが、 native function では型は後置なんですね。
だからどうということではないですが…。
