### ISSUE TITLE
Is there a way to define struct or record?

### ISSUE THREAD

**Issue by t-k-** [Kray-G/kinx#160]
I am looking for some language like this, thank you for making it opensource! It looks awesome!

As so far I have read, it seems the documentation has not mentioned how to define structure, anyway to do it?

Also  is there a way to interact with C libraries or headers? And, does it have a pointer type?

**Comment by Kray-G** [comment]
Thanks for your kind comment. It motivates me.
I am very sorry the documentation has not been completed yet. and I feel sorry if I got misunderstanding what you want to say.

### Data Structure

The kinx is a prototype based design like JavaScript, so in general, data structure will be defined as a JSON object like the following.

```javascript
var data = {
   prop1: "something",
   prop2: "anything",
};
```

But to do more the object oriented programming style, the `class` keyword can be used for making its purpose clearly and packaging data and methods. The description of `class` is [here](https://kray-g.github.io/kinx/spec/definition/class.html).

```coffeescript
class A {
    var private_;

    private initialize() {
        @prop1 = "somethig";
        @prop2 = "anythig";
    }

    public get() {
        return private_;
    }
}
```

### Interface for C library

It is possible to do interact with C library like below.

* Preparing a C library file. It should be a .dll or .so file with API to talk with Kinx. The template is here. For example, it is named `something.c` and it will be compiled to `something.dll` or `something.so`
```
#define KX_DLL
#include <kinx.h>
#include <kxthread.h>

int method_hook(int args, kx_frm_t *frmv, kx_frm_t *lexv, kx_context_t *ctx)
{
    int64_t arg1 = get_arg_int(1, arg, ctx);
    const char arg2 = get_arg_str(2, arg, ctx);

    // ... example
   int count = printf("number = %d, comment = %s\n", arg1, arg2);

    // return value
    KX_ADJST_STACK();
    push_i(ctx->stack, count);
    return 0; // 0 means a normal end.
}

static kx_bltin_def_t kx_bltin_info[] = {
    { "method", method_hook },
};

KX_DLL_DECL_FNCTIONS(kx_bltin_info, NULL/* dll initializer */, NULL/* dll finalizer */);
```

* Use it in Kinx source code by `_import` keyword.
```
// loading something.dll or something.so and binding methods.
var Something = _import("something");

// Something object have a method named as `method`.
// this will display "number = 10, comment = aaa", and r will be a count of printed chars.
var r = Something.method(10, "aaa");
```

As a pointer type, of course it can be used in C code but it can not directly used in Kinx script. It has to be handled in C code. When I want to do it, I use `kx_any_t` type and hold it in the property of the created object.

For example, [`kxregex.c`](https://github.com/Kray-G/kinx/blob/master/src/extlib/kxregex.c) uses a pointer.

* Creating a Regex object in `Regex_create()` function in C. It is bound to `Regex.create()` and it is used as `new Regex()`. (`new Regex()` is absolutely same as `Regex.create()` in Kinx).
* In `Regex_create()`, using a `kx_any_t` type and hold it to the property of `_pack` inside a regex object. `kx_any_t` type can hold a method to free it to the property of `any_free`. This function will be called on GC.
* The methods of Regex object will use it by getting it from a `_pack` property by `KX_GET_RAW` macro.

It might be not enough, but I am happy it would be helpful for you.

Thank you very much to ask this.
I will do work to complete documentation.

**Comment by t-k-** [comment]
@Kray-G Thanks you for such a detailed answer.

The reason I am asking is because structure feature (to create a linear memory space with a protocol) is usually missing, and it can be very useful say in Network package parsing. I would wish for some dynamically typed language can also introduce `struct` like what C is doing.

I see you can import the ABI level C exports, but I think the one-direction import is a shortcoming since people may hesitate to get in this language, with their existing C/C++ project for example, because later it is impossible to quit and go back.

Do you think it is possible to introduce Type (and optional type checking?) other than kx_any_t into this dynamical language? It may also help to export to a C.

**Comment by Kray-G** [comment]
@t-k- 
Thanks for a description. Let me confirm to understand what you said.

If my understanding is correct, I feel it is possible to implement it, although it has been not implemented yet.
Currently, there is `binary` type, which is not structured and it is nothing but a byte array.
I feel it can be realized by extending binary, and mapping it to the structured data.
Maybe... I have to consider an endianness (big or little).

Here is my assumed code. Is this same as what you want?

```javascript
// Defined a structured type in Kinx.
struct Data { seq: int64, data: uint8[24] };

// JSON data on right hand side will be casted to structured Data object which size is just 32 bytes.
var data: Data = { seq: 10, data: [ 1, 2, 3, 4 ] };

// data is structured type, so accessing by the field property is available.
System.println(data.seq) // => 10;
System.println(data.data[0]) // => 1;

// data is also binary, so accessing by index is also avaiable.
System.println(data[8]); // => 1

// Data can be used as array. (not a kinx array, just sequential items of Data)
// Kinx Array on right hand side will be casted to 64 bytes (32 x 2) binary data.
var dataArray: Data[] = [Data, { seq: 11, data: [ 2, 2, 3, 4 ] }];

// Index and a property access is available as a structured type.
System.println(dataArray[1].seq) // => 11;
System.println(dataArray[1].data[0]) // => 2;

// dataArray is also binary, so accessing by index is also avaiable.
System.println(dataArray[8]); // => 1
System.println(dataArray[40]); // => 2
```

To realize it, I will have to do a lot of work.
I will think about this. And thanks for suggestion. I feel enjoy to think of another feeling to the language.

If I did misunderstanding, please let me know, and I am very sorry.

**Comment by t-k-** [comment]
Yes, that is what I mean, basically a C structure. But, shouldn't the endianness depend on the architecture? Unless you revert each byte manually to enforce consistent behavior, But that would be inefficient.

also, do you want explicit casting to byte array when you operate index on that Data struct?
Anyway it looks good to me and it is what I wished for.

**Comment by mingodad** [comment]
I think that what you are asking is already implemented here https://github.com/vovkos/jancy

**Comment by Kray-G** [comment]
@mingodad Thanks for the information!
I will see Jancy to understand it. The purpose as a language seems to be different but the keyword is **Safe Pointer**.
Basically it is a statically typed but it has a structure named `dynamic structs` and its size will be got by `dynamic sizeof`.
It is very interesting.

Anyway, I may not be able to make it realize soon, but I will try to consider the way to handle a structured data easily in Kinx as a dynamic typed language.

Many thanks.

**Comment by t-k-** [comment]
@mingodad After glance through it, I think that is pretty much what I wished for, thanks for sharing it! I cannot wait to dive into its documentation for more details.

**Comment by t-k-** [comment]
@Kray-G No worry, I like the way Kinx is heading for, keep on the work! I am closing this issue now so no stress :P
