### ISSUE TITLE
Could be a good idea to mention that this is only for x86_64 ?

### ISSUE THREAD

**Issue by mingodad** [Kray-G/kinx#161]
When I tried to compile this project on an ARM64 I noticed that it depends on executing the binary in  utility/kmyacc that is only x86_64 for linux and windows.

So no other operating systems like OSX, ANDROID, FREEBSD, AIX, ...

If this is a limitation of this project I think that is a good idea to specify it clearly on the README.

**Comment by Kray-G** [comment]
Thank you for your comment. I am sorry to confuse you.

I believe it can make this project suit other platforms, but I could not prepare it so far. For instance, I do not have any ARM environment so I could not do it for ARM.

I will add some description into README as you said.

To suit this to another platform, there are not only kmyacc but also some what I have to do.

1. utliity/kmyacc problem, but it will be not a big problem.
    * kmyacc can be recompiled for the target platform  because it is also an open source on [GitHub/kmyacc](https://github.com/Kray-G/kmyacc).
    * As alternative way, I can commit the parser file after proceeded by yacc.
    * Or I can replace kmyacc by bison. kmyacc will generate a smaller and a better table than bison, but in fact, I used bison before but I did replace bison by kmyacc. (I am now using kmyacc because I respect the author of kmyacc, see details in [GitHub/kmyacc](https://github.com/Kray-G/kmyacc))
2. There are some dependent libraries in this repo. I think it is not a good way but I am doing it for convenience. Those libraries are put under `src/extlib` folder. Some are located it as a source code but some are located as a pre-built component. Currently there are 6 projects which is prepared as a pre-built component such as  libcurl, libharu, libssh2, libxml2, openssl, and zip(minizip).
    * Preparing a folder for the target platform and prebuilding and putting a library under that folder each library.
    * Preparing Makefile for the target platform to compile with above libraries.

To be honest, I am strongly considering I would like to suit a lot of platforms, but I am sorry I don't have a environment and time to do that now...

Anyway I should make it clearly on README.
Thank you very much for your suggestion.

**Comment by Kray-G** [comment]
I did try to add a supported platform to [README](https://github.com/Kray-G/kinx/blob/master/README.md).
Could you please check it.

Thanks again.

**Comment by Kray-G** [comment]
This issue is closed once.
If there's a lack of information, please reopen this or open an issue as another one.
