### ISSUE TITLE
native function での除算

### ISSUE THREAD

**Issue by htsign** [Kray-G/kinx#17]
#16 で返信をする際に改めて native function を触っておりましたが、どうも native function 内で浮動小数の除算が行われると結果が不定になるようです。

以下、全て同じ実行環境で確認しています。

|OS|CPU|Kinx|
|---|---|---|
|Windows 10 (2004) x64|AMD Rizen 1600|v0.8.1|

```typescript
function half(n) {
  return n / 2;
}
native<int> nativeIntHalf(n: int) {
  return n / 2;
}
native<dbl> nativeDblHalf(n: dbl) {
  return n / 2;
}

System.println(half(4.5));          // 2.25
System.println(nativeIntHalf(4));   // 2
System.println(nativeDblHalf(4.5)); // 9.88131e-324  (？)
```

行を切り貼りして function call の順番を変えると `0` を出力したりします。
剰余算でも確認しました。加算・減算・乗算では特に問題が見受けられませんでした。

---

なお、別件となりますが native function 内で小数のリテラルを書くとエラーになります。
書くだけでエラーになります。呼び出す必要はありません。

```typescript
native f() {
  return 1.0;  // Assertion failed at d:\a\kinx\kinx\src\jit/sljitLir.c:1411
}
```

---

これも別件になりますが通常関数に型宣言を書いてもエラーになりません。
（これは別に実害がないのでどうでもいいかもしれません）

```typescript
// approved!
function addOne(n: int) {
  const ONE: int = 1;
  return n + ONE;
}
System.println(addOne(42)); // 43
```

**Comment by Kray-G** [comment]
ありがとうございます！（そして申し訳ありません...）
色々情報が少ない中、試していただいてすみません。上から順に回答すると、以下の通りです。

1. 除算に関して
    * 現時点で未実装のステータスです。
    * 実際問題として native では未実装の部分がいくつか残っており、代表的なものでは各種比較が未実装（かつエラーしない...）状態となっています。

2. 実数リテラルに関して
    * 実装されていましたが不具合でした。。。

3. 通常での型宣言に関して
    * 期待通りの動作ですが、現時点では役に立っていません。
    * 将来的には型情報を使った最適化や on the fly での JIT などに使えるかなー、と思ってそうしているのですが、時間の関係で手がついていません...
        * 型が不一致になってもエラーにすらしていません...

といった状況です。

もうそろそろバージョン番号が 1.0.0 に近づいてきたので、区切りをつけて Version 1.0.0 としてリリースしてしまおうと思ってるのですが、native 周りはあまり正式サポートとしては出しづらいかな、と思っています。

ただ、native 周りは Kinx の特徴的な機能ではあるので、今後もちょっとずつ進化させていければとは考えております。

ひとまず、1, 2 できちんと動くようにしてみます！

> 実装していないところに時間を割かせてしまって、ほんとに申し訳ありません :sweat:。

**Comment by Kray-G** [comment]
fixed this by the commit of 2b559daceffb12752947e374e8e82514e9e5f7c2.

**Comment by htsign** [comment]
> 現時点で未実装のステータスです。

なるほど、そうだったのですね。そう言えばまだ Kinx は pre-release でした…。
わざわざ優先順位を変更してまで実装して下さいましてありがとうございます。
急かすような形になってしまい申し訳ないです。

> 将来的には型情報を使った最適化や on the fly での JIT などに使えるかなー、と思ってそうしている

Kinx のモジュールでは `Integer` や `Double` となっているのに対して型が `int` `dbl` なのは TypeScript における `number` と `Number` や Java における `int` と `Integer` みたいな差なのでしょうか？
（すなわちプリミティブとオブジェクトの差）

**Comment by Kray-G** [comment]
あまり深く検討はしていなかったのですが、以下の理由で区別しました。ただ、`Integer`、`Double` を使ったほうが表現に一貫性があっていいのかな...、ということで若干気持ちに揺れがあったりもします（←ブレてますね...）。

* `Integer`、`Double` は型名ではなくオブジェクト（ただし特殊オブジェクトの扱い）
* `Integer` の表す数値は `Big Integer` を含む。native 関数内の `int` は `Big Integer` へのオート・プロモーションは無く、単純にオーバーフローする。
* 型名はヒント情報なので、長いと単純に書くのが面倒なのと、言葉が主張しすぎるとソースコードが読みづらくなりそう（直観的にですが...）。Java のソースコードで時々感じる「重い」感じになりそうで、それを避けたかった（表面上、軽い感じが良い）。

なので、プリミティブかオブジェクトか、という差というわけではなく、オブジェクト（`Integer`、`Double`）か単なる情報（型情報/ヒント）なのか、という感じで区別してました。

良い意味でまだ `pre-release` なので、仕様変更も含めてもう少し考えてみます。

ありがとうございました！

**Comment by htsign** [comment]
ご返答ありがとうございます。お考えを拝聴できて有意義でした。

> Java のソースコードで時々感じる「重い」感じになりそうで、それを避けたかった

確かにこれはありそうですね…。
見た目のインパクトは大文字の方が大きい気がします。書く方もしんどいですし。

型ヒントが `Integer` でなく `int` になるなど「軽い感じ」を目指すとなると、ユーザー定義型の変数に対して型ヒントを付けるというのは将来的にもあまり考えていない感じでしょうか？
あるいは Java のように組み込み型とそれ以外は明確に分ける？
もしくはユーザー定義型にも自分で「軽い」シンボルを別に定義できるような仕組みを設けるとか、
それとも #16 で示させていただいた通りドキュメントコメントで補完するからいいという考えでしょうか。

ともあれ 2b559daceffb12752947e374e8e82514e9e5f7c2 は既に `master` にマージされておりますので、本 Issue は一旦 close します。

**Comment by htsign** [comment]
[Qiita の某記事](https://qiita.com/zettaittenani/items/3bb25752d6e6a458332e)を見ていて気になり Kinx で素数判定の関数を書いてみたのですが、どうもまだ除算については正確な動作とは言えないような気がいたします。

```javascript
function isPrime(n: int) {
    for (var i = 2; i <= Math.sqrt(n); ++i) {
        if (n % i == 0) return false;
    }
    return true;
}

System.println(isPrime(15) ? 'true' : 'false'); // false
System.println(isPrime(17) ? 'true' : 'false'); // true
```

```javascript
native isPrime(n: int) {
    for (var i = 2; i <= Math.sqrt(n); ++i) {
        if (n % i == 0) return false;
    }
    return true;
}

System.println(isPrime(15) ? 'true' : 'false'); // true
System.println(isPrime(17) ? 'true' : 'false'); // true
```

`function` を `native` に置き換えただけで結果が異なってきます。  
これが本当に除算のせいなのかどうかまでは問題の切り分けができていないのですが…。

**Comment by Kray-G** [comment]
@htsign さん

ご連絡ありがとうございます！
確かに。。。

調査してみます。
少々お待ちください。

**Comment by Kray-G** [comment]
チョンボでした。。。
剰余計算において、SLJIT に SLJIT_DIVMOD_SW という命令があるのですが、これは R0 レジスタに割った値を、R1 レジスタに余りを格納してくれます。ここで、なぜか R0 を使ってしまっていました（つまり割り算と同じことを...）。

今日は時間がないのですが、native の通常ケースのテストコードを用意したいと思います。

まずはお礼まで。。。
ありがとうございました。

**Comment by Kray-G** [comment]
@htsign さん、お世話になっております。
本件の修正を含め、v0.18.0 でリリースしました。ご確認いただければと思います。
なお、v0.18.0 は別で起こした https://github.com/Kray-G/kinx-language-server 向けの修正を入れています。
やっと Language Server 作り始めましたので、ご興味あれば覗いていただければ幸いです。
使えるものになりましたら、リリースする予定です。

**Comment by htsign** [comment]
本件正しく動作しているのを確認できたのでCloseします。
ご対応ありがとうございました！
