### ISSUE TITLE
test has failed

### ISSUE THREAD

**Issue by htsign** [Kray-G/kinx#19]
2b559daceffb12752947e374e8e82514e9e5f7c2 のテストから[失敗しています](https://github.com/Kray-G/kinx/runs/727484224?check_suite_focus=true#step:7:1)。

実はこのエラー、fork した方の私のリポジトリでも（`Kray-G/kinx/master` と `htsign/kinx/master` に差異がないにも関わらず）再現したことがありました。
その際には `_function` を `function` に変えてスタックトレースを追ってみるとかいろいろやったのですが、知識不足もあり結局原因が分からず、リポジトリを一旦削除して作り直しています。

re-run jobs すると結果が変わることがあり（ジョブをキックする本来ユーザーから見えない .sh がコケていたりした） GitHub 側の問題も疑ってみましたが、今改めて私の方で `git pull --rebase upstream master && git push` してみたところ、いきなり[同じエラーでコケていた](https://github.com/htsign/kinx/runs/729683297?check_suite_focus=true#step:7:1)ので、もしかしたら本当に `kxstartup.kx` に問題があるのかもしれません。
もしくは私の yaml の書き方が悪く、ジョブ毎のタイミングが悪かったりしているのかも…。

**Comment by Kray-G** [comment]
ご連絡ありがとうございます！
気づいていませんでした。。。が、思い当たる節があります。。。

恐らく原因は 07241ac136794d693aed1f5c8baabf8d2e1cb6d8 のコミットです。ここで `$exepath` という kinx のインストールパスを取得できる変数を追加したのですが、`kxsystem.dll` を新しくしないと確かに Method Missing が発生してしまいます。

一旦これまでの修正もあるので V0.9.0 としてタグを打ってリリース・バージョンを作成すると正しく動作するかと思います。

ローカルでは失敗していないので、一旦リリースすることにします。

ご連絡ありがとうございました。

**Comment by htsign** [comment]
なるほど。そういうことでしたか…！
やはり過去の tags から .tar.gz を落としてきてテストに使用するというのはよくないかもしれないですね。
Linuxの方のビルドは2分もかからなかったはずですので（それでも `tar zxvf` よりはずいぶん遅いですが…）都度ビルドしてテストを走らせるように yaml を変更してみます。

---

> 再現したことがないので何とも言えないですが、似たようなケースを想定すると、バイナリが古い状態で残っていた場合、というのが考えられるかもしれません。

ホストは docker ベースで動いていると予想していて毎回まっさらな環境になっていると考えていたので、その可能性は目から鱗です。

---

ちなみに

> 気づいていませんでした。。。

については catch されないエラーがあった場合でも 0 で終了していることによると思われます。
SpecTest はエラーで non-zero なので合わせるとよいかと愚考します。

**Comment by Kray-G** [comment]
たしかに non-zero で合わせたほうが良いですね。`kxstartup.kx` でコケることは想定していなかったのですが、そうなった場合、開発時点ではキャッチされずに Uncaught exception のほうが目で見えて分かりやすいので、両方できるように細工を検討してみます。

ありがとうございました！
