### ISSUE TITLE
Here Document

### ISSUE THREAD

**Issue by T-I-Oak** [Kray-G/kinx#2]
about "Here Document" in readme.md.

I think it is a literal of a string, not a here document.

Almost 'Here Document' is separated of the code line, like as follows.

```
var a = %{HEREDOC}.trim();
This is here documen.
New line is available in this area.
HEREDOC
```
And I don't think 'Here Document' is necessary...

**Comment by Kray-G** [comment]
Okay I did correct it also with https://github.com/Kray-G/kinx/commit/eaede269d349304f137c6e9ffba7e3a86ea5f3db.

About actual here document as you said,
I will think if it is necessary and will do it if needed.

Thank you very much.
