### ISSUE TITLE
`print`, `println` の出力をオーバーライドする方法

### ISSUE THREAD

**Issue by htsign** [Kray-G/kinx#3]
試しにこのようなコードを書いていました。  
よくある Option(Maybe) の簡易実装です。

```javascript
class Option { }

class Some(value) : Option {
    var NotFuncErr = RuntimeException("'fn' must be function type.");

    public map(fn) {
        throw NotFuncErr if (!fn.isFunction);

        var next = fn(value);
        return next.isUndefined ? Option.none : Option.some(next);
    }
    public filter(fn) {
        throw NotFuncErr if (!fn.isFunction);

        return fn(value).isUndefined ? Option.none : this;
    }
    public flatMap(fn) {
        throw NotFuncErr if (!fn.isFunction);

        var next = fn(value);
        throw 'type mismatch' if (!next.instanceOf(Option));

        return next;
    }
    public toString() {
        return 'Some(%{value})';
    }
    public count() {
        return 1;
    }
    public isSome() {
        return true;
    }
    public isNone() {
        return false;
    }
}
class None : Option {
    public map(_) {
        return this;
    }
    public filter(_) {
        return this;
    }
    public flatMap(_) {
        return this;
    }
    public toString() {
        return 'None';
    }
    public count() {
        return 0;
    }
    public isSome() {
        return false;
    }
    public isNone() {
        return true;
    }
}

Option.of = &(value) => value.isUndefined ? new None() : new Some(value);
Option.some = &(value) => new Some(value);
Option.none = new None();
```

その上で、

```javascript
var opt = Option.of(3);

System.println(opt);
System.println(opt.toString());
```

としたとき、出力は

```console
[...]
Some(3)
```

でした。

ここで、オブジェクトの文字列化について内部実装を拝見したところ、 `kx_format` という関数を呼んでいるところまでは分かったのですが、勉強不足ゆえそれ以後の処理を追いきれませんでした。  
[`objval->type != KX_OBJ_T`](https://github.com/Kray-G/kinx/blob/65dea8c91d9db4b9d9a86de61849c38c54bc234c/src/format.c#L182) を満たしたら `[...]` になりそう、というのはなんとなく分かりました。

というのを踏まえた上で、クラスなどの独自オブジェクトについて文字列化を行うときの規則を制御する方法はあるのでしょうか。

**Comment by Kray-G** [comment]
おお、なるほど。実はすみません。これは現在はできておらず、私もサポートしたいと思っていたものの一つで、どこかで入れたいと思っていました。というのも、例えば `Array#join` や、`Array#toString` もそうなのですが、オブジェクトが `toString` メソッドを持っていたらそれを適用した上で本来の処理を適用する、という形に修正したいと思っていました。（`System.print/println` に対してこれが期待する動作であっていますでしょうか?）。

上記で解釈が間違っていなければ、対応する予定ですので少々お待ちいただければ幸いです。

> `kx_format` は単純に C 形式のフォーマットを処理する部分で、`%4d` や `%-20s` 等を処理するモジュールになります。一応位置指定子も使えるようにしたので、`%1%` や `%2%` で位置を指定することも可能です。混ぜる場合は `%2$x` といった形で使います。フォーマット文字と型が合わない場合は勝手にそれっぽい文字に置き換えます（整数値なら `%d` 等）。

**Comment by htsign** [comment]
お返事ありがとうございます。

> オブジェクトが `toString` メソッドを持っていたらそれを適用した上で本来の処理を適用する

まさしくそのような動作を望んでおりました。  
対応予定とのことで安心いたしました。

> `kx_format` は単純に C 形式のフォーマットを処理する部分

なるほど、そうでしたか。こちらはあまり関係なかったのですね。

**Comment by Kray-G** [comment]
Feature requested:

* Applying an object to `System.print` or `System.println` after using the `toString` method when the object has the `toString` method.
* It had better support this stringify strategy when it is `Array#join` and `Array#toString` as well.

**Comment by Kray-G** [comment]
@htsign さん、お世話になっております。
色々と余計なことをしていたせいでリリースが遅れました... が、プレビュー [v0.5.1](https://github.com/Kray-G/kinx/releases/tag/v0.5.1) に本修正を入れてみました。もしよろしければお試しいただければ幸いです。

* https://github.com/Kray-G/kinx/releases
    * https://github.com/Kray-G/kinx/releases/tag/v0.5.1

**Comment by htsign** [comment]
@Kray-G ありがとうございます！  
 `toString()` を持ったオブジェクトを `println` に渡したときに期待通りの出力となりました！

ただし、以下のように気になる点もありました。

```javascript
// ["[""[1, 2]"", ""[3, 4]""]", "[""[5, 6]"", ""[7, 8]""]"]
System.println([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]);
```

```javascript
class MyObj(value) {
    public toString() {
        return 'MyObj(%{value})';
    }
}

// OK.
// MyObj(42)
System.println(new MyObj(42));

// NG.
// Uncaught exception: No one catch the exception.
// SystemException: Unsupported operator
// Stack Trace Information:
//         at function MyObj#toString(../kxobject/myobj.kx:3)
//         at <main-block>(../kxobject/myobj.kx:7)
System.println(new MyObj(new MyObj(42)));
```

重箱の隅のようなケースですが、ご確認お願い致します。

**Comment by Kray-G** [comment]
@htsign さん、お世話になっております。
いえ、テストしていただいているみたいで非常に恐縮です。正直申し訳ない感じですが、非常に助かります。ありがとうございます。修正してみました（[v0.5.2](https://github.com/Kray-G/kinx/releases/tag/v0.5.2)）。

```
[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
MyObj(42)
MyObj(MyObj(42))
```

先ほどの例では上記のように表示されることを確認しました。

* https://github.com/Kray-G/kinx/releases/tag/v0.5.2

まだいろいろ見つかるかもしれません。温かい目で見守っていただければ幸いです。

**Comment by htsign** [comment]
@Kray-G 重ねてありがとうございます！  
仰る通り、正しく表示されるようになりました。

diff を拝見して演算子も定義できることに気付き、そこでも少し遊ばせていただいています。  
Haskell や Scala などのように何でも無秩序に定義できるわけではなさそうですね。

**Comment by Kray-G** [comment]
@htsign さん、良かったです！
演算子オーバーライドは悩みどころですが、プリミティブ型の演算子オーバーライドは公式にはサポートしない方針にしようかな～、と考えています。
Ruby のように `1+1` の意味も変えられる、というのは体系的には一貫した思想もあって美しいとも思うのですが、実際問題としては弊害が大きく…
ただし、クラス・オブジェクトに対する演算子はオーバーライドできるデメリットはなく有益なので、正式にサポートを表明しようかと思っています。例えば以下のように書けます（書けるはず…）。

```javascript
class A {
    public +(rhs) { ... }
}
var a = new A();
a + 1;  // a.+(1)
```

`==`, `!=`, `>`, `>=`, `<`, `<=`, `<=>`, `+`, `-`, `*`, `/`, `%` が定義できます（できるはず… まだテストできてませんが）。

本当にテストしていただいているようで恐縮なのですが、また何かあればぜひぜひ issue 報告頂けると有難いです！

一先ず本 issue は close といたしますが、今後ともよろしくお願いいたします。

**Comment by Kray-G** [comment]
Here is a sample of operator override for the class instance.

```javascript
class IntVal(value_) {
    @isIntVal = true;
    public clone() {
        return new IntVal(value_);
    }
    public value() {
        return value_;
    }
    public add(rhs) {
        if (rhs.isInteger) {
            value_ += rhs;
        } else if (rhs.isIntVal) {
            value_ += rhs.value();
        } else {
            throw RuntimeException("Unsupported operation");
        }
        return this;
    }
    public +(rhs) {
        return @clone().add(rhs);
    }
    public println() {
        System.println(value_);
    }
}
var a = new IntVal(100);
var b = a + 1;
var c = b.+(1);
a.println();  // => 100
b.println();  // => 101
c.println();  // => 102
```

Works good.
