### ISSUE TITLE
Syntax conflict with `switch-else`.

### ISSUE THREAD

**Issue by Kray-G** [Kray-G/kinx#336]
Now we can not write the code below because it is conflict between `if` and `else`.

```
switch (a) {
when 10:
    if (b) {
         /* */
    }
else:  // => Syntax error.
    /* something */
}
```

This is a restriction so far, but it should be solved if possible.

**Comment by Kray-G** [comment]
I am now planning it could be the `otherwise` keyword.
It will be used not only with `switch-when` but also `case-when`.

**Comment by htsign** [comment]
IMO, one of objective in this project is "like C syntax". so, I think `default` is good too.

**Comment by Kray-G** [comment]
Thanks for the comment!

`default` has been already used and it works with fall through.
`else` was introduced instead of `default` and it expects to work without fall through.

The problem is, that we need something like `default` without fall through, so `else` was introduced, but the name is not good for the situation.

That is why I come up with the `otherwise` keyword.
This keyword seems to be used in MATLAB.

**Comment by htsign** [comment]
I see. I had forgotten keywords related fall through😂

**Comment by Kray-G** [comment]
refs: 65139b1fa92c9eca8c978dedd240e70312aa1ef9

**Comment by Kray-G** [comment]
Now you can write it below.

```
switch (a) {
when 10:
    if (b) {
         /* */
    }
otherwise:
    /* something */
}
```

And also you can still use `else`, but I may make it deprecated in the future.
