### ISSUE TITLE
Is there a CLI or IDE for Windows?

### ISSUE THREAD

**Issue by HAHEU** [Kray-G/kinx#4]
Hello, does the kinx language have IDE or CLI compiler for development environment?

**Comment by Kray-G** [comment]
Hello @HAHEU ,
Thanks for your question & for your interest in my product.

Now Kinx have no IDE, but CLI is `kinx.exe` just to run the script on the fly.
If you mean the CLI is what to generate a native code or a precompiled code file like Java class file, the answer for your question is unfortunately no.

To be honest, I have a plan to be able to output a precompiled file but I guess it will not meet in time of the target of the version 1.0.0...

About IDE, I think it is good to be done on the Visual Studio Code. Currently I don't have any idea, but if doing it, I'd like to develop it as VS Code extension.

Is this to be an answer for your question?

**Comment by HAHEU** [comment]
Yes, thank you

**Comment by HAHEU** [comment]
Hi @Kray-G,
Can you create a project file so that it can be compiled more easily for Visual Studio? (.Sln extension)

The Vs 2017 command system does not compile

**Comment by Kray-G** [comment]
Now I am trying to create a project, but it hasn't been completed yet because of a little complex. Sorry I do not use Visual Studio IDE, instead I am usually using VS Code & nmake with Visual C/C++.
Anyway I will continue to try but I am sorry I can't promise when it is provided. Please wait for it.

By the way what you mean VS2017 could not compile this? That is `nmake -f Makefile.msc` would be failed?

One of what I know is the compiling `ir_exec.c` on Windows with VS2017 takes too long time, estimated about 30 to 40 minutes on my desktop.  With gcc 7 on Linux, it is very short and takes only 15 seconds.

If you have a trouble on compiling it, please let me know the details.

**Comment by HAHEU** [comment]
Hi @Kray-G 

> timex cl /c /nologo /O2 /MT /Iinclude /Isrc/jit /DYYMALLOC=kx_malloc /DYYFREE=kx_free /Fosrc/ir_exec.obj /Fasrc/ir_exec.s src/ir_exec.c
> ir_exec.c

When I write this command it stays here and does not continue.

**Comment by Kray-G** [comment]
Hi @HAHEU,

Sorry, that is one of what I know about VS optimization, but it is working correctly. Just taking a long time of compilation. I think I will try to be improved, but currently it takes 30 or 40 minutes in my environment.

I think it is the problem but it is the problem of Visual C's optimization, so it will not become fast even if you use IDE of VS2017. If we make a optimization be off, the compilation time is fast but the execution performance will be very slow. Therefore I decided I would wait for the long time compilation so far.

Could you please check it?
Thanks in advance.

**Comment by nishantc1527** [comment]
I have a suggestion for the IDE (all though the repl is great). You can make an Intellij plugin (it's not that hard, tons of tutorials) and you can make plugins for other IDE's too.

**Comment by Kray-G** [comment]
@nishantc1527 
Thanks for the comment. Yes I absolutely agree with you.
I want to try to make a plugin of Visual Studio Code if I have time, but I haven't started yet so far.
And also I am considering what a debugger should be.

**Comment by Kray-G** [comment]
This is just for your information.
The compile time of ir_exec.c has been decreased from around 40 minutes to around 10 minutes.
I do not check the actual reason, but I guess the reason why it become shorter is the change of the mechanism of handling exceptions.
Anyway I will let you know the compile time of ir_exec.c is now becoming shorter.

**Comment by Kray-G** [comment]
I have started developing a language server of Kinx in VSCode extension.
See https://github.com/Kray-G/kinx-language-server.
It is still on the early stage, but it is one of an answer for this issue.
Therefore let me close this issue once.

Welcome a question anytime.

Thanks in advance.
