### ISSUE TITLE
最後にコールバックを受ける関数の糖衣

### ISSUE THREAD

**Issue by htsign** [Kray-G/kinx#48]
提案です。
本リポジトリに多くのKinxライブラリが実装されていくにつれ、最後の引数にコールバック関数を取る関数が多く見られます。
これらは「関数を取る場合はそれが最後になる」という点で一貫しているように思えます。

そこで、「関数を最後に取る関数を呼び出すとき、最後に渡す関数はパーレンの外側に出せる」という構文規則を増やせないものでしょうか。

```coffee
function f(a, b, fn) {
    return fn(a, b);
}

# これを
const result1 = f(1, 2, &(a, b) => a + b);
System.println(result1); # 3

# こう書けるように
const result2 = f(1, 2) &(a, b) => a + b; # syntax error in current kinx
System.println(result2); # 3?
```

この考えは [Swift](https://docs.swift.org/swift-book/LanguageGuide/Closures.html#ID102) や [Kotlin](https://kotlinlang.org/docs/reference/lambdas.html#passing-a-lambda-to-the-last-parameter), [Nim](https://nim-lang.org/docs/manual_experimental.html#do-notation) などからヒントを得ています。
Ruby は外側にしかブロックを置けなかった（はず）なので参考から除外しています。

```swift
// Swift
func f<T>(_ a: T, _ b: T, fn: (T, T) -> T) -> T {
    return fn(a, b)
}

let result1 = f(1, 2, fn: { $0 + $1 })
print(result1) // 3

// equivalent of above
let result2 = f(1, 2) { $0 + $1 }
print(result2) // 3
```

```kotlin
// Kotlin
fun <T> f(a: T, b: T, fn: (T, T) -> T) = fn(a, b)

fun main() {
    val result1 = f(1, 2, { a, b -> a + b })
    println(result1) // 3
    
    // equivalent of above
    val result2 = f(1, 2) { a, b -> a + b }
    println(result2) // 3
}
```

上手く適用できると、読む側にとって優しいコードになれる可能性があります。
パーサー書く側にとっては辛くなりそうですが…。

**Comment by Kray-G** [comment]
@htsign さん、ご提案ありがとうございます！

そのやり方は、以前できるといいカナー、と思ったことがありますが、見た目は JavaScript ぽくないカナー、とか、既存の手段があるのでサポートする意味があるカナーとか考えてやってませんでした。

ただ、使いやすくなる可能性がありそうとのことなので、ちょっとトライしてみますね！

構文解析さえうまく行けば（問題なければ）あとはそれほど難しくはないと思います（たぶん…）。

**Comment by htsign** [comment]
@Kray-G ご考慮ありがとうございます！
Kinxは文末のセミコロンが必須なので解釈の曖昧さについては問題ない（式の後にブロックが続く可能性を排除できる）と思っていますが、仰る通りJSっぽくはなく、Cファミリーらしさを念頭に置いた言語での提案に悩みました。
ですが、便利であれば考えていただけるとのことでよかったです。

**Comment by Kray-G** [comment]
構文をチェックした結果、仰る通りブロックはコンフリクトしないのですが、以下 2 つでコンフリクトします。なので、ちょっと検討しました。

```javascript
const result2 = f(1, 2) &(a, b) => a + b;
    // 以下 2 つで曖昧（アローの後ろの式は `a` のみか `a + b` までか）
    // (f(1, 2) &(a, b) => a) + b
    // (f(1, 2) &(a, b) => (a + b))

function g() { return 0x101; }
var x = g() & 0xff;
    // `&` が来た時に shift/reduce conflict となる（＝shift を選択となる）ので、上記で syntax error となる。
```

そこで、以下のようなスタイルを考えてみました。

```javascript
var c = 100;
function f(a, b, callback) {
    return callback(a, b);
}

// アロー（`=>`）の場合は `{` `}` でくくる（式の最後にセミコロンは不要）。
var r = f(2, 10) { &(a, b) => a + b } + c;
System.println(r);

// ブロックを渡す場合は、ブロックの内側（の最初）に引数リストを記載。アローも不要。
var r = f(3, 10) { &(a, b)
    return a + b;
};
System.println(r);

// 単にブロックを渡した場合は、引数無しの関数ブロックとして認識。
var r = f(4, 10) {
    return c;
};
System.println(r);
```

これだとコンフリクトせずに構文解析できそうです。
いかがでしょうか？

**Comment by htsign** [comment]
ありがとうございます。
コンフリクトの例、気付きませんでした。レビューいただき助かります。

> `var r = f(2, 10) { &(a, b) => a + b } + c;`

なるほど、これなら確かに大丈夫そうです。
ただ、ケースによって記法が異なってしまうと不要な混乱を生みそうかな？とも思いました。（Nim が正にそのパターンなので前例はあるのですけど）
私のはあくまで提案であり最終的な決定は当然 @Kray-G 様にあるので、判断はお任せします。

---

> 試してみると $1 が最初の引数っぽいイメージがあったのと、Ruby の Numbered parameters も _1～ なので、$1または_1～ がよさそう。

Ruby のケースは元々 `@1` も有力な候補にあったところ、[インスタンス変数と混同する](https://bugs.ruby-lang.org/issues/15723#note-126)という事情によりやむなく `_1` になったという経緯があるので…。
と思いましたが Kinx も `this.` のエイリアスが `@` でしたね。

あるいは [Groovy](https://groovy-lang.org/closures.html), [Kotlin](https://kotlinlang.org/docs/reference/lambdas.html#it-implicit-name-of-a-single-parameter) の `it` や [Perl](https://perldoc.perl.org/perlvar.html#General-Variables), [PowerShell](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_automatic_variables?view=powershell-7#_) の `$_` など、仮引数が1つのラムダのみ特殊記法を用意して、2つ以上の場合には素直に書かせるという方針もあります。
[Scala](https://scala-lang.org/files/archive/spec/2.13/06-expressions.html#method-values), [Nemerle](https://github.com/rsdn/nemerle/wiki/Quick-guide#anonymous-functions-and-partial-applications) では式本体における仮引数の出現順が与えられる引数の順に等しいときに使える `_ + _` などといった感じの記法もありますね。

**Comment by Kray-G** [comment]
@htsign さん、
コメントありがとうございます！
Ruby は `@` だと思っていたらいつの間にか `_` に代わっていました（気づいてなかったです :sweat_smile:）。

混乱するという点に関しては、まぁコールバック用のブロック定義の部分だけなのでコールバックを使いたい人は使い分けられるかな、というのと、そもそも `&` をその場所に配置できず従来とは全く同じ書き方にはできないため、若干の違いは許容することにしたいと思います。

どのようなシンタックスを許すことにしたかは下に書きますが、いくつか考えてみた点に関して備忘録的に残しておきます。

* 見た目は既に JavaScript と違うところもあるし、C ライクという点では `{` `}` でブロックを表す、とかは踏襲しているので、便利に使えるなら良いでしょう。
* というか、関数呼び出しの閉じカッコが同じ行に収まって、コールバック用の定義だけ独立して書けるので、確かに便利、見た目も良い。
* プレースホルダ（`_1` ～ `_9`）が使えると引数リストが省略できて思った以上に楽。同じなので普通の関数定義でも使える。
* プレースホルダは `_` を使うことにしよう。`$` は通常の変数に使える文字だが、`_` で始まるキーワードは予約語扱いにしているので（←どっかに書いたっけ? ... 書いて無ければ書いておく）。
* `@` も `this.` のエイリアスで使っているのでやめておく。
* 式とステートメントを区別しないといけないが、どちらをデフォルトにするか。
    * 式をデフォルトにする場合、`{ _1 * 2 }` のように書けるようにして、ステートメントの場合は何かアノテーションする。
    * ステートメントをデフォルトにする場合、`{ return _1 * 2; }` と書けるようにして、式のみのほうに何かアノテーションする。
    * ステートメントにアノテーションするのはこれまであまりないのとブロック定義の見た目と変わる。普通のブロックのように書けなくなる。`{ => var a; a = _1 + 10; return a; }` とかになるとちょっとイヤ。
    * 式は式で直接書けるとすっきりするが、多少追加があっても単純だし関数式は `&(a) => a` みたいに `=>` が付いてる。
    * 色々考えたが、ブロックで複数ステートメントを記載する場合に、ブロック構造として従来と同じ形にできることを優先。式には `=>` を付けることとする。
    * 結論 -> 式：`{ &(a) => a * 2 }`、プレースホルダ版：`{ => _1 * 2 }`
    * 結論 -> ブロック：`{ &(a) return a; }`、プレースホルダ版：`{ return _1 * 2; }`
* 式の要素（factor）ではない部分にブロックが現れたらコールバックなので、その場合は関数呼び出しだと思って解釈させてしまうと `[1,2,3].map { => _1 * 2 }` みたいに関す呼び出しのカッコが省略できる。これはこれで便利そう。この際だからできそうなことは全部入りにしてしまおう。
* 全部入りということで、`{ &(a) return a; }` は ``{ &(a): return a; }` と書いても良いことにする。なんとなく区切りが欲しい人向け。
* `_` も入れてみる。出現順に `_1`、`_2` と割り当たっていく形。
* 思いついたの全部入りと言いつつ、`{ |a,b| return a+b; }` は解釈自体はできるがやめておこう（さすがにこれはやり過ぎか）。意味的に Ruby と違う（配列とかでは同じ動きをしない）のでこれは逆に混乱するだろうなー。

ということで、完成形は以下になります。

```coffeescript
var c = 100;
function f(...args) {
    var callback = args.pop();
    return callback(...args);
}

# This is a normal style.
var r = f(2, 10) { &(a, b) => a + b } + c;
System.println(r);

# Do not have to put the parameter list.
var r = f(2, 10) { => _1 * _2 } + c;
System.println(r);

# Can put a statement after a parameter list.
var r = f(3, 10) { &(a, b) return a + b; };
System.println(r);

# ':' is available for distinguishing parameters and a statement list.
var r = f(4, 10) { &(a, b): return a + b; };
System.println(r);

# Can put a statement list directly without a parameter list.
var r = f(5, 10) { return _1 * _2; };
System.println(r);

# No sense, but it is okay without statements.
var r = f(6, 10) { &(a, b) };
System.println(r.isUndefined);

# This means nothing to do, it can be used for ignoring callback, etc.
var r = f(7, 10) {};
System.println(r.isUndefined);

# Arguments can be accessed via special placeholders from _1 to _9.
var r = f(8, 10) { return _1 + _2; };
System.println(r);

# `_` is assigned to a placeholder according to the order of appearance.
var r = f(9, 10) { return _ + _; }; # same as `_1 + _2`
System.println(r);

# This is an example of multiple statements and assignment to the argument placeholder.
var r = f(9, 10, 11) {
    _4 = 10;    # A value can be assigned.
    return _1 + _2 + _3 + _4;
};
System.println(r);

# This is an example of map().
var r = [1, 2, 3].map() { => _1 * 2 };
System.println(r);

# The parenthesis can be omitted when the arguments is a callback function only and it is given by a block.
var r = [4, 5, 6].map { => _1 * 2 };
System.println(r);

# This is another example of omitting a parenthesis.
var r = (1..10).sort { => _2 <=> _1 };
System.println(r);
```

結果。

```
112
120
13
14
50
1
1
18
19
40
[2, 4, 6]
[8, 10, 12]
[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
```

**Comment by htsign** [comment]
思った以上にたくさんの文法が導入されましたね😂
identity function が `{ => _ }` でいいのはとても楽でいいですね。

> 混乱するという点に関しては、まぁコールバック用のブロック定義の部分だけなのでコールバックを使いたい人は使い分けられるかな、という

混乱するというのは「読み手にとって」という意味でした。が、恐らく Kinx のユースケースとしては他人に公開するより個人で簡単な処理の自動化としてちょこちょこバッチ組むような場合だと思われるので問題ないかもですね。

ひとまず本Issueはcloseします。ご対応ありがとうございました！

**Comment by Kray-G** [comment]
@htsign さん、お世話になっております。
続報です。

構文解析でのコンフリクト条件を調べていた所、実は通常のブロックと同じになるケース以外（つまり、`{` の後に `=>` か `&` が来るケース）では、factor としてコールバック用の構文がそのまま使えることが分かりました。
なので、コールバックと全く同じ書き方が関数の引数部分に書くことができるため、通常こちらの書き方にしておくとコールバック時の書き方と同じ書き方ができるようになることが分かりました。

```javascript
var r = (1..10).sort { => _2 <=> _1 };
System.println(r); // => [10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
var r = (1..10).sort({ => _2 <=> _1 });
System.println(r); // => [10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
```

またこの対応をしたことで、通常の式や関数呼び出しの任意の引数の場所でこの構文での記載ができるようになりました。

```javascript
function func(f, ...p) {
    return f(...p);
}

System.println(func({ => _ * 2}, 10)); // 20

var callback = { => _ * 3};
System.println(func(callback, 10));    // 30

var r = { => _ * 4}(10);
System.println(r);                     // 40

var r = (&{ return _ * 5; })(10);
System.println(r);                     // 50
```

引数無しのブロックを書くときは従来通り `&` を使って回避（`&{ ... }`）を付けた上で `(` `)` でくくる必要があります（うーん、オブジェクトとコンフリクトする場合があるので、現状これはどうしようもないな...）。無理やり解釈するとしたら、コールバック構文（外出しの構文）の場合には '&' が省略できる...、でしょうか。

> コミットログに本チケットへのリンクを付けていなかったのですが、変更点は 67b2557b2e2a39ff2ec294c1a35c899aaebc80c7 です。

以上、今後ともよろしくお願いいたします。

**Comment by htsign** [comment]
すごいですね！
今どき即時関数を使うメリットもそうないですが（JavaScript が関数スコープの `var` しか持っていなかった頃の名残りだと思ってます）、軽量構文で書けること自体は非常に歓迎すべきことだと感じました。
個人的にはもはやアローの方しか使わないかもしれません…。
